version: 2

updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"

- package-ecosystem: go:modules
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 40
