version: '3.8'

services:
  nats:
    image: nats
    networks:
      - mk
    ports:
      - 4222:4222
      - 8222:8222

  postgres:
    image: postgres
    networks:
      - mk
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

networks:
  mk:
    name: mk
    driver: bridge
