name: Test and coverage

on:
  push:
    branches:
      - main

jobs:
  coverage:
    name: Test and Coverage
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [ 1.19.x ]

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: 'postgres'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run coverage
        run: |
          go install github.com/jandelgado/gcov2lcov@latest
          go test ./... -race -coverprofile=coverage.out -covermode=atomic
          gcov2lcov -infile=coverage.out -outfile=coverage.lcov

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage.lcov
          
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
